name: Add SSoC26 Label

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSoC26 label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: SSoC26
          github_token: ${{ secrets.GITHUB_TOKEN }}
